package main

import "github.com/edrumm/markup"

func main() {
	/*
		Create new html page
		(*HTML)
	*/
	index := markup.HtmlPage("index.html", "en", "A Markup Page")

	// Add some elements to body
	index.Body(
		markup.Tag("h1", "Auto Generated Page"),
		markup.SingleTag("hr"),

		// Tag with nested tags
		markup.Tag("p",
			"An HTML page generated by Markup Go package",
			markup.SingleTag("br").Html(),
			markup.Tag("strong", "Some subtext").Html(),
			"and back to normal...",
		),

		markup.Hyperlink("https://pkg.go.dev/github.com/edrumm/markup", "Markup on pkg.go.dev"),
		markup.SingleTag("br"),
		markup.SingleTag("br"),
		markup.ImgWithSize("1024px-Go_Logo_Blue.svg.png", "Go logo", 341, 128),
	)

	/*
		Div tag
		(*HtmlDiv)
	*/
	div := markup.Div()

	// Fill div with some content
	div.Content(
		markup.Tag("h2", "Div Header"),
		markup.Tag("p", "Some div text"),
	)

	// Add div to body
	index.Body(div)

	/*
		Create new stylesheet
		(*Stylesheet)
	*/
	css := markup.NewStylesheet("style.css")

	// Render page to html file
	index.Render()

	// Render stylesheet to css file
	css.Render()
}
