package main

import "github.com/edrumm/markup"

func main() {
	/*
		Create new html page
		(*HTML)
	*/
	index := markup.NewHtmlDoc("index.html", "en", "A Markup Page")

	// Append elements
	index.AppendBody(markup.NewTag("h1", "Auto Generated Page"))
	index.AppendBody(markup.NewSingleTag("hr"))
	index.AppendBody(markup.NewTag("p", "An HTML page generated by Markup Go package"))

	div := markup.NewDiv()
	div.AppendToDiv(markup.NewTag("h2", "Div Header"))
	div.AppendToDiv(markup.NewTag("p", "Some div text"))

	index.AppendBody(div)

	/*
		Create new stylesheet
		(*Stylesheet)
	*/
	css := markup.NewStylesheet("style.css")

	// Render page to html file
	index.Render()

	// Render stylesheet to css file
	css.Render()
}
